global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  # web:
    # address: ':80'
  agent:
    address: ':5051'
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"
        - "10.0.0.0/8"
      insecure: false
  relay:
    address: ':6061'
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"
        - "10.0.0.0/8"
      insecure: false
  server:
    address: ':7071'
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"
        - "10.0.0.0/8"
      insecure: false
  traefik:
    address: ':8081'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: phirepass-network
  file:
    watch: true
    filename: /traefik.yml

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  format: common
