services:

  traefik:
    image: traefik:3.6.9
    user: "0:0"
    security_opt:
      - label=disable
    ports:
      - "6061:6061"
      - "7071:7071"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:Z
    networks:
      - phirepass-network
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=phirepass-network"
      - "--entryPoints.server.address=:7071"
      - "--entryPoints.relay.address=:6061"
      - "--entryPoints.agent.address=:5051"

  server:
    image: dimitrmok/phirepass-server:0.1.154
    env_file: .env
    environment:
      - PORT=7071
    networks:
      - phirepass-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/`)"
      - "traefik.http.routers.server.entrypoints=server"
      - "traefik.http.services.server.loadbalancer.server.port=7071"
      - "traefik.http.routers.server-ws.rule=PathPrefix(`/api/nodes/ws`)"
      - "traefik.http.routers.server-ws.entrypoints=server"
      - "traefik.http.routers.server-ws.service=server"

  relay:
    image: dimitrmok/phirepass-relay:0.1.154
    env_file: .env
    environment:
      - PORT=6061
    networks:
      - phirepass-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.relay.rule=PathPrefix(`/`)"
      - "traefik.http.routers.relay.entrypoints=relay"
      - "traefik.http.services.relay.loadbalancer.server.port=6061"
      - "traefik.http.routers.relay-ws.rule=PathPrefix(`/api/web/ws`)"
      - "traefik.http.routers.relay-ws.entrypoints=relay"
      - "traefik.http.routers.relay-ws.service=relay"

  agent:
    image: dimitrmok/phirepass-agent:0.1.154
    env_file: .env
    depends_on:
      - server
    environment:
      - PORT=5051
      - SSH_HOST=host.docker.internal
    volumes:
      - ./secrets:/secrets:ro
      - agent-data:/home/nonroot
    command: ["start", "--token-from-file", "/secrets/access_token.txt"]
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - phirepass-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent.rule=PathPrefix(`/`)"
      - "traefik.http.routers.agent.entrypoints=agent"
      - "traefik.http.services.agent.loadbalancer.server.port=5051"
      - "traefik.http.routers.agent-ws.rule=PathPrefix(`/api/web/ws`)"
      - "traefik.http.routers.agent-ws.entrypoints=agent"
      - "traefik.http.routers.agent-ws.service=agent"

volumes:
  agent-data:
    name: agent-data

networks:
  phirepass-network:
    name: phirepass-network
